
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from tkinter import Tk, Canvas, PhotoImage, Toplevel
from pathlib import Path
from tkPDFViewer import tkPDFViewer as pdf

def questions():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Toplevel()

    window.geometry("615x865")
    window.configure(bg = "#FEECEC")

    canvas = Canvas(
        window,
        bg="#FEECEC",
        height=865,
        width=615,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    canvas.place(x=0, y=0)
    '''
    image_image_11 = PhotoImage(
        file=relative_to_assets("image_6.png"))
    image_11 = canvas.create_image(
        72.56494617462158,
        75.18830966949463,
        image=image_image_11
    )

    image_image_9 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_9 = canvas.create_image(
        69.0,
        74.0,
        image=image_image_9
    )

    image_image_10 = PhotoImage(
        file=relative_to_assets("image_8.png"))
    image_10 = canvas.create_image(
        357.0,
        326.0,
        image=image_image_10
    )

    canvas.create_text(
        196.0,
        80.0,
        anchor="nw",
        text="Na te pytania odpowiem:",
        fill="#000000",
        font=("HachiMaruPop Regular", 20 * -1)
    )

    canvas.create_text(
        254.0,
        118.0,
        anchor="nw",
        text="pytania",
        fill="#000000",
        font=("HachiMaruPop Regular", 20 * -1)
    )'''
    v1 = pdf.ShowPdf()
    v2 = v1.pdf_view(window, pdf_location=open("Pytania_do_Bota.pdf","r"),  width=300, height=300, bar=False)
    v2.pack()

    window.resizable(False, False)
    window.mainloop()
